name: Build and Deploy WASM

on:
  push:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build WASM
        run: |
          mkdir -p docs
          GOOS=js GOARCH=wasm go build -o docs/main.wasm ./src/*.go

      - name: Commit and push WASM
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/main.wasm
          git commit -m "自動ビルド: docs/main.wasm更新" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
